### ISSUE TITLE
Cannot upload photo from Ubuntu

### ISSUE THREAD

**Issue by drivet** [electerious/Lychee#375] opened 2015-07-11 15:32 UTC
I've installed the latest Lychee on Ubuntu Server 14.04.  I installed PHP 5.5.9, and nginx 1.4.6.  The installation appeared to work okay.

When I try uploading a photo (IMG_0023.jpg), I get this in the browser:

"Photo type not supported! Please take a look at the console of your browser for further details."

I'm not sure what the "console of your browser" is, but if you mean the Diagnostics, I see this:

Diagnostics
Warning: Dropbox import not working. No property for dropboxKey
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
No critical problems found. Lychee should work without problems!

System Information
Lychee Version:  3.0.3
DB Version:      030003
System:          Linux
PHP Version:     5.5
MySQL Version:   50543
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      2.1.1-dev
Plugins:         

If I run the Show Log from the setting menu, I get this:
2015-07-11 11:20:39 America/New_York - error - Photo::add (98) 	- Photo type not supported

Not sure where to go from here...

**Comment by TwizzyDizzy** [comment] 2015-07-17 12:31
You might try raising your PHP ini-settings - I just ran into the same problem and it worked, despite the misleading error message

> upload_max_filesize
> post_max_size

post_max_size should be slightly larger than upload_max_filesize.

Cheers
Thomas

**Comment by electerious** [comment] 2015-11-15 19:44
Is this issue still present? If yes, could you attach some photos casing the error?

**Comment by drivet** [comment] 2015-11-15 20:15
It was present the last time I tried to use Lychee.  I don't believe modifying upload_max_filesize or post_max_size did anything.

**Comment by electerious** [comment] 2015-12-22 12:21
Will close the issue as I'm not able to reproduce it.

**Closed by electerious** 2015-12-22 12:21 UTC
