### ISSUE TITLE
Duplicate Uploads

### ISSUE THREAD

**Issue by dotcomUNDERGROUND** [electerious/Lychee#433] opened 2015-12-18 00:43 UTC
When I am trying to a bit large (around 100) number of files (less than 1mb each) with the Drag and Drop uploader, mostly I am getting duplicated copies of the photos. Even like same photo 5 times.

I have just made an upload of 136 photos (total size 14MB). The album ended up with 431 photos! 

Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey
Error: Upgrade to PHP 5.5 or higher

System Information
------------------
Lychee Version:  3.0.7
DB Version:      030003
System:          Linux
PHP Version:     5.4
MySQL Version:   50545
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      bundled (2.1.0 compatible)
Plugins:

**Comment by electerious** [comment] 2015-12-20 11:29
Which browser are you using? Could you try it in another one?

**Comment by dotcomUNDERGROUND** [comment] 2016-01-05 09:41
Sorry for the delay getting back.

I was using Google Chrome (on windows 10). 

I have just tested uploading 51 pics (4.5mb in total) using FireFox. The album ended up having 87 pics.

**Comment by electerious** [comment] 2016-01-08 14:02
That issue is new to me. Never heard about something similar :-/ I don't know why this could happen.

**Comment by dotcomUNDERGROUND** [comment] 2016-01-23 16:05
Upgraded PHP to 5.6. Still experiencing the issue.

173 images turned into 512

Is there any way to debug the issue? Turning on special logging or something?

btw, under diagnostics i see a warning:
<b>Warning</b>:  session_start(): Cannot send session cache limiter - headers already sent (output started at /home/****/public_html/plugins/check/index.php:25) in <b>/home/****/public_html/plugins/check/index.php</b> on line <b>107</b><br />

**Comment by electerious** [comment] 2016-01-24 12:10
That's not the reason for your problem, but thanks a lot for letting me know :) Will be fixed in the next version.

You could take a look at the Lychee log (Settings -> Show Log), but I'm not sure if there's something relevant to find. You could also try a fresh Lychee installation with a new database.

**Comment by dotcomUNDERGROUND** [comment] 2016-01-24 16:51
Making a fresh install will mean i'll lose all my albums/photos and will have to upload them again I believe? Won't be a suitable thing for me to do unfortunately. Unless there is a way to make server side export.

On the log files I see some entries like:
notice - Photo::add (223) 	- Skipped adjustment of photo 
But its just for a few files. 

However in top I see some old entries as:
2015-03-31 22:15:09 - error - Photo::add (191) 	- Duplicate entry '14278185091000' for key 'PRIMARY'
2015-03-31 22:24:26 - error - Import::server (128) 	- Could not import folder. Function returned warning
2015-03-31 22:24:26 - error - Photo::add (191) 	- Duplicate entry '14278190663100' for key 'PRIMARY'
2015-03-31 22:24:41 - error - Import::server (128) 	- Could not import folder. Function returned warning
2015-03-31 22:24:41 - error - Photo::add (191) 	- Duplicate entry '14278190812300' for key 'PRIMARY'

Can it be something related to apache or php limits? Like apache timeout causing to retry uploads over and over even through actually it got uploaded?

Btw, thanks a LOT for your very very active support!

**Comment by VictorLamoine** [comment] 2016-02-01 21:25
:+1: I am affected too.
I've been updating Lychee since version c4798ce16f7e255c10b321635779ac7d53275a16; it is now up to date (c0c924fc13c3b675de06167a95fcbd803b0e4148).

I'm using Mozilla Firefox on Ubuntu 14.04 to upload the pictures, some end up being upload 4 times, some 3, some 2, some 1.

**Comment by electerious** [comment] 2016-02-05 23:03
Good to know that there are at least two with the same problem. Lets start debugging!

> I've been updating Lychee since version c4798ce; it is now up to date (c0c924f).

Which was the last working version for you?

> some end up being upload 4 times, some 3, some 2, some 1.

- Is this completely random?
- What happens when you delete the uploaded one (and all duplicates) and reupload the photo. Does it always appear with the same amount of duplicates?
- Does it happen with JPGs only or also with other photo formats?
- Are there some images which are always fine?
- Are there special characters in the filename?

> Making a fresh install will mean i'll lose all my albums/photos and will have to upload them again I believe? Won't be a suitable thing for me to do unfortunately. Unless there is a way to make server side export.

No need to delete your current installation. The second one would be just for testing purposes.

Thanks for helping!

**Comment by VictorLamoine** [comment] 2016-02-05 23:35
> Which was the last working version for you?

Sorry... Can't tell which was the latest working version, I don't keep track of that info :smile: 


I've done some tests by uploading a set of 60 pictures several times (each time in a new album), I tested different downsizing of the pictures to vary the weight of the file.

It looks like file size has a role in this bug, uploading light (~60kb / file) set of pictures works ok (0 duplicate).
When uploading the same set of pictures in a decent resolution (~500 kb / file) I get duplicates.


>    Is this completely random?

Yes, uploading the same set of files two times does not produce the same duplicates.
Images that were not duplicate can appear duplicated. Images that were duplicated can be uploaded without duplicates.

>    What happens when you delete the uploaded one (and all duplicates) and reupload the photo. Does it always appear with the same amount of duplicates?

Uploading a single photo never leads to a duplicate. (I believe the parallel upload feature has something to do with this bug)

>    Does it happen with JPGs only or also with other photo formats?

I did not tested other formats

>    Are there some images which are always fine?

No

>    Are there special characters in the filename?

No, simply "DSC00614.jpg" and alike.

**Comment by VictorLamoine** [comment] 2016-02-05 23:48
I've just reproduced the issue in a fresh install of Lychee trunk (c0c924fc13c3b675de06167a95fcbd803b0e4148).
After the upload "pop-up" is closed the page flickers (with no thumb images loaded) like 4/5 times before the pictures finally appears.

**Comment by electerious** [comment] 2016-02-06 11:24
Thanks for the feedback @VictorLamoine :)

> I believe the parallel upload feature has something to do with this bug)

Possible. Maybe Lychee sends the file multiple times to the server. Could you record the network activity using the [network inspector of your browser](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor)? It should only send one request per file.

**Comment by VictorLamoine** [comment] 2016-02-06 12:18
Here is a .har file of the upload (I did it with Chromium)
https://mega.nz/#!xJkXTYDR!Xy1NLvaFv7rdK34IUXlDuea75TDd1nkfZeFVGo2ohKE

**Comment by electerious** [comment] 2016-02-06 13:45
There're several requests for the same files. Seems to be a client-side issue. I will take a look at [it](https://github.com/electerious/Lychee/blob/master/src/scripts/upload.js#L41).

**Comment by VictorLamoine** [comment] 2016-02-29 23:00
Do you have a fix for this bug?
Or maybe need more data?

**Comment by electerious** [comment] 2016-03-04 22:23
Haven't found what's casing the problem, yet. I will try to upload a test-script in the next time so we can continue to test.

**Comment by karlak** [comment] 2016-03-20 22:49
I have the same issue with the latest commits of the develop branch.
The client seems to upload multiple times the same files when uploading a lot in a batch.

**Comment by electerious** [comment] 2016-03-21 08:24
@karlak Which browser and system are you using? Could you attach the diagnostics, too?

**Comment by qligier** [comment] 2016-03-21 11:00
It seems that `xhr.upload.onprogress` function gets sometimes called twice when the file is uploaded (progress = 100), so the `process` function get also called twice and all following files are uploaded twice. It's really infrequent (something like 0.2 or 0.3% chance).

On the following screen, the red line shows the two calls that both launch the next photo processing. Then all photos are processed twice.
![upload_duplicate2](https://cloud.githubusercontent.com/assets/3299399/13916677/5866a446-ef5c-11e5-80e7-8db60d065d71.png)

**Comment by electerious** [comment] 2016-03-21 14:26
Please switch to the develop-branch and let us know if everything works fine now.

Thanks to @qligier for the PR. He starts to own the changelog for version 3.1.

**Comment by electerious** [comment] 2016-03-29 16:41
Lychee 3.1 is out and the issue should be fixed. Thanks everyone for the help!

**Closed by electerious** 2016-03-29 16:41 UTC
