### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by bravobih** [electerious/Lychee#389] opened 2015-08-14 14:13 UTC
I installed Lychee on my computer and it is working fine. But when I've installed it on some free web server I get a message on a blank brown screen "Server error or API not found".  I think the problem is in php/define.php script with LYCHEE definition. Is there any way to check which API not found ?

**Comment by electerious** [comment] 2015-08-15 09:15
Please check and post the output of the diagnostics (http://yourdomain.com/lychee/plugins/check/index.php). You can also try to take a look at the console of your browser. Maybe it includes some additional information.

**Comment by burgerkingGH** [comment] 2015-08-29 01:15
I am trying to install Lychee on a Raspberry pi 2. I am getting the same error as above. It took me a while to figure out how to run the script. Visiting the script page just returned a 502 bad gateway error. In case it helps anyone, this worked for me:

sudo apt-get install php5-cli
cd /var/www/Lychee
php plugins/check/index.php

... Here is the error message of the script:

Diagnostics
-----------
Error: Configuration not found. Please install Lychee for additional tests

I thought I 'installed' lychee by following the instructions found at http://www.pihomeserver.fr/en/2014/01/23/raspberry-pi-home-server-heberger-toutes-vos-photos/

Namely, I used:
sudo git clone https://github.com/electerious/Lychee.git

I have found no answers to this issue after hours of searching.

Thank you!

**Comment by electerious** [comment] 2015-09-05 21:35
@burgerkingGH Make sure the site is accessible via a browser. Otherwise you can't configure and use Lychee. Based on the error it looks like you never continued beyond step 12.

**Comment by burgerkingGH** [comment] 2015-09-20 16:32
Thank you for the reply. I was not able to continue beyond step 12 exactly because of the error described. Trying to visit the site via a browser brought up a bad gateway error. Are there additional configurations that might be needed beyond what is listed?

**Comment by electerious** [comment] 2015-09-29 19:59
"Bad gateway error" sounds like there's something wrong with your server configuration. I would recommend to ask this question elsewhere, as this has nothing to do with Lychee itself. You can continue with the installation as soon as you can open the interface.

**Comment by electerious** [comment] 2015-09-29 20:01
I'm closing this issue as I can't reproduce the problem reported by @bravobih. More information necessary.

**Closed by electerious** 2015-09-29 20:01 UTC

**Comment by geerk** [comment] 2016-01-29 20:01
Sorry for reopening this issue,but I have the same error. and I cant configure Lychee because it shows empty page in browser: 
<img width="1440" alt="2016-01-29 21 59 47" src="https://cloud.githubusercontent.com/assets/723297/12686682/d36f6af8-c6d3-11e5-9964-1f374d2cb7e7.png">

**Comment by geerk** [comment] 2016-01-30 07:46
I have found the problem. I have followed instructions from dockerfile and there is a mistake in nginx conf. instead of `include fastcgi_params;` I wrote `include fastcgi.conf;` and all works now.
See

**Comment by romjean** [comment] 2016-04-22 12:21
Hello there,
I've the same problem as @bravobih .
Here below the result of the page http://mydomain/lychee/plugins/Diagnostics/index.php:

> Parse error: syntax error, unexpected T_STRING in /mnt/130/sdb/f/a/12m2duhavre/photos/plugins/Diagnostics/index.php on line 9

It's a free domain so I guess that some features are not activated. Could you help me ?
Thanks
RomJean

**Comment by electerious** [comment] 2016-04-22 12:28
@romjean This error happens mostly because of incorrectly configured servers. What's the PHP version your are using? You shouldn't get an error when visiting the Diagnostics.

**Comment by romjean** [comment] 2016-04-22 17:25
The PHP version is 5.1.3RC4-dev, see phpinfo(); result below
RomJean
<img width="606" alt="phpinfo" src="https://cloud.githubusercontent.com/assets/15798122/14749483/f53bdcce-08bf-11e6-957e-0f1a2b82ec8f.png">

**Comment by qligier** [comment] 2016-04-22 17:33
You need PHP >= 5.3.
