### ISSUE TITLE
Secure share URL

### ISSUE THREAD

**Issue by toddritt** [electerious/Lychee#27] opened 2013-11-17 20:07 UTC
Some other less design-friendly photo gallery systems offer a feature that I am requesting in Lychee: the ability to share an album with a private URL that wouldn't require a password.  That way the photos are still relatively private, but the users don't have to enter a password.  For instance, http://photos.mysite.com/Wedding?key=123456789

**Comment by PeterTheOne** [comment] 2015-01-08 13:30
+1

**Comment by umpf** [comment] 2015-02-28 15:15
+1 
btw: great work so far, thank you

**Comment by toerb** [comment] 2015-08-29 22:04
+1, any news?

**Comment by yang** [comment] 2016-01-05 14:55
+1

**Comment by Bramas** [comment] 2016-01-05 15:40
This feature almost exists already, since it is possible to have a not visible shared album. The only problem is that the url is easily guessable because the auto incremented id is used.

* One way could be to simply change the id in the database to be a random string instead of an auto incremented int. The shared protected url will exist without implementing new stuffs. Only few things must be change in the implementation (the generation of the id and the default ordering base on the creation date instead of the id)
* Another way is to add a field such as uid that contains a random string and that is used instead of the id in the url of the album.
* The last way is to check for the password in the url. when the album request the password, if the url contains a password parameter, then it is used by default to open the album. So that we just have to add ?pass=thepassword to the url of the album when sharing so that it become a protected shared url. (the problem is that it is not by default append in the input that appears when you click on the share button)

I also really want this feature, so if Tobias knows how he want it to be implemented, I can do it.

**Comment by iangreenleaf** [comment] 2016-01-05 18:47
On Tue, Jan 5, 2016, at 07:40 AM, Bramas wrote:
>  * The last way is to check for the password in the url. when the
>    album request the password, if the url contains a password
>    parameter, then it is used by default to open the album. So that we
>    just have to add ?pass=thepassword to the url of the album when
>    sharing so that it become a protected shared url. (the problem is
>    that it is not by default append in the input that appears when you
>    click on the share button)

I wonder if this might be the easiest way to add the feature in a
friendly way and not introduce too much code complexity.

For *public*  albums, they should still be findable by the short id,
which will keep backwards compatibility and is much nicer - having a
huge string of random letters in the URL is annoying if you don't need
it. But *private* albums must be findable only with some sort of secret.
Using the password as this secret would mean you wouldn't have to change
any of the access control code. You'd only need to update the share link
to include the password, Maybe as a bonus feature, private albums could
offer a "share private link" option that would set a long randomly
generated password and pop up the share input (saving people the process
of setting their own password if all they want is a direct link).

**Comment by NoodleBB** [comment] 2016-01-06 13:46
:+1: +1

**Comment by Klikini** [comment] 2016-02-24 01:34
I found this thread because I don't like having guessable URLs for my albums. Even though most of my albums are not checked as public, you can just increment the #id to find them all.

I think it would be best to assign ids of a few random characters so that they would be harder to guess (like `#5uh234t5f`), or even make it an option to customize the URL to with options like `#my-album-name` or `#rAnd0mChARS`.

Just a thought, and it shouldn't add too much code. Only a textbox or radio buttons in the sharing UI and a function in the database interaction code to set the non-sequential IDs.

I might have time this weekend to play around with it (I haven't looked at this project's code yet) if nobody else has a working implementation yet.

**Comment by electerious** [comment] 2016-02-24 20:51
@Klikini Lychee uses the microtime for the photo ID. Could do the same for albums to make them less guessable. Thought about this a while ago as invisible albums are easy to find by incrementing the ID.

**Comment by prat0088** [comment] 2016-02-25 10:38
+1 from me, specifically for sharing collections and all albums in them.

**Comment by Klikini** [comment] 2016-02-26 00:37
@electerious That's exactly what I wanted to do: unguessable IDs for _all_ albums, but shared ones would still be listed on the site.

**Comment by electerious** [comment] 2016-03-12 23:29
New album id now based on the microtime (like photos). This makes it harder to guess them. The sharing dialog has been updated: "Visible" now named "Hidden". Should make things more clear.

This feature will be part of the next release :)

<img width="615" alt="lychee - asdasdasd" src="https://cloud.githubusercontent.com/assets/499088/13725944/71e4257a-e8b2-11e5-970c-360082386305.png">

**Comment by Klikini** [comment] 2016-03-13 13:40
Awesome!

**Comment by electerious** [comment] 2016-03-15 12:37
This feature will be part of Lychee 3.1.

**Closed by electerious** 2016-03-15 12:37 UTC
Labels: enhancement
