### ISSUE TITLE
[Feature] User Access Control / Multiuser

### ISSUE THREAD

**Issue by djdallmann** [electerious/Lychee#132] opened 2014-04-24 14:24 UTC
Here's some ideas for access control that I would like to see, I haven't really looked at the code so I’m not sure how hard this would be. 

You'd probably have to create a table that would define users and their permissions to each album then have a php/js script determine what albums should be displayed and that would also limit access based on those permissions. It might also be a good idea to keep some of the session data stored on the server if it isn't already, that way you could compare the session identifier token to the username that the request was being performed as and validate that they match before executing any functions; this would assist to mitigate a malicious user from executing commands/actions as another user.

Superuser
Full access to view/modify all albums and photos

Standard
Per album view control  (who can or can't view album x)
Per album upload control (who can or can't upload to album x)
Per album and photo delete option (who can or can't delete photos from album x)

Read Only
Can only read/view images for explicitly defined albums.

**Comment by ftairs** [comment] 2015-01-06 15:59
+1

**Comment by PeterTheOne** [comment] 2015-01-08 13:08
+1

**Comment by electerious** [comment] 2015-01-08 13:20
Would be great if everyone could tell a bit about their use-case of this feature: Do you just want multiple users or multiple users with different permissions? What permissions should be adjustable? Are there other potential settings for users?

**Comment by PeterTheOne** [comment] 2015-01-08 13:25
I would like to give some users permission to view some private albums..

**Comment by electerious** [comment] 2015-01-08 13:26
Current state of this issue: I'm currently rewriting parts of the front-end, including the dialog system. The new one will make it easier to display complex settings, which are required for a "User Access Control". Don't expect this feature soon. It requires a lot of changes and Lychee is only a side-project. It's on the roadmap and has a high priority.

**Comment by electerious** [comment] 2015-01-08 13:28
@PeterTheOne Public protected albums aren't working for you in this case? How about this: https://github.com/electerious/Lychee/issues/27 ?

**Comment by PeterTheOne** [comment] 2015-01-08 13:33
#27 would be great yes! But frequent users of my gallery would potentially have to save a lot of links, so it would be nice if they had gallery permissions linked to their user account.

**Comment by electerious** [comment] 2015-01-08 13:37
@PeterTheOne A password protected collection would be what you need: https://github.com/electerious/Lychee/issues/254 Could contain all albums for one group and they only need to input the password once.

**Comment by PeterTheOne** [comment] 2015-01-08 13:45
@electerious also nice but imagine many different parties, holidays, etc. with different guests. Some are family events that I share with my family, some are event with my friends. Some guests are very often the same (need user accounts) but some change for every occasion (could deal with a link/password).

**Comment by zuloo** [comment] 2015-01-08 13:53
+1 @PeterTheOne 
revoking access rights - for any reason - would lead to a new password protectd collection or at least a new password for everybody who still is allowed to view.

**Comment by lebochequirit** [comment] 2015-01-15 20:15
My user case:
I have a couple of friends (a pro will have customers) I'd like to share photos with. Not every friend/client shall see every album, so I need a user list, maybe groups (for a group of friends) and per photo/per album-settings to decide who may watch what.

I must admit that I meanwhile moved to piwigo where I found that feature already implemented very well. If you decide to keep lychee as lean as possible piwigo might be a recommendation for those whose needs are not met.

L.B.Q.R.

**Comment by moorestudios** [comment] 2015-01-30 21:13
+1

**Comment by wongalan2002** [comment] 2015-02-09 10:17
+1

**Comment by NxtGenCowboy** [comment] 2015-02-10 17:10
+1

**Comment by Oozemeister** [comment] 2015-03-09 18:20
+1

**Comment by tmlmt** [comment] 2015-03-24 21:35
+1

**Comment by ohhdemgirls** [comment] 2015-03-25 13:37
+1

**Comment by salyh** [comment] 2015-04-10 11:27
+1

**Comment by BenoitDuffez** [comment] 2015-04-19 15:06
Re: _Would be great if everyone could tell a bit about their use-case of this feature: Do you just want multiple users or multiple users with different permissions? What permissions should be adjustable? Are there other potential settings for users?_

My use case would be to have one super user (me), and other users (my wife, parent, etc.) which would have upload rights, and the ability to edit sharing options of their albums.
The super user would have every right on every album.

**Comment by tmlmt** [comment] 2015-04-19 18:36
I simply won't install Lychee until this feature is implemented. 

Here is what I would like:
- 1 super-user ("admin") and an unlimited number of normal users
- Super user rights: list/create/edit/delete users, view/create/edit/delete/share albums, upload pictures
- Normal user rights = any combination of those six: view, create, edit, delete, upload, share
- Per user defaults rights for any new album
- Per album view/create/edit/delete/upload/share control
- Share options: password or user-based

**Comment by xxcram** [comment] 2015-04-28 12:14
**Re: Would be great if everyone could tell a bit about their use-case of this feature: Do you just want multiple users or multiple users with different permissions? What permissions should be adjustable? Are there other potential settings for users?**

We will use Lychee for an internal image library with multiple users (admins). As an addition we like to share some albums to our customers (maybe multiple albums to one customer).
- Admin (upload photo, create album, edit metadata) - **as it is now, maybe ability for multiple admins**
- User (visit/download selected albums) - **new**
- Guest (visit/download shared album) - **as it is now**

At the moment I can share just a single album (not multiple inside the same link) to a customer and have to select every album as invisible to hide them.

**Comment by Enoch247** [comment] 2015-04-28 14:30
Re: Would be great if everyone could tell a bit about their use-case of this feature: Do you just want multiple users or multiple users with different permissions? What permissions should be adjustable? Are there other potential settings for users?

My use case is for storing/archiving (and optionally sharing) family photos. I'd like the ability to have users and grant read or read-write permissions to users on a per album basis. Each user(wife, kids, etc) could create new albums which they would own and be able to share with other users. Anyone with read access should also be able to publicly share an album via emailed link facebook, etc.

If you've ever used ownCloud. I think it's file sharing model is about as good as it gets. Check out its federated sharing feature. Also the ability to grant write access to albums via public link (without creating a new user) is useful as no one wants to have to create new accounts for every extend family member (and then constantly reset their passwords for them). Thats the pie-in-the-sky goal for my installation.

**Comment by pmichelazzo** [comment] 2015-04-28 19:10
My case in close of the Enoch247 case. I just need to give permission for family members to upload photos, create albums and share the content (optionally too).

One bit more: users can create "private" albums where no one, except the owner can see/share/edit.

Regards

**Comment by electerious** [comment] 2015-04-30 20:38
Thanks for all the comments. There aren't any news about this feature, but it still has a high priority and will make it into a version after 3.0. Keep posting your use-cases, they're a big help! :)

**Comment by JanWerder** [comment] 2015-05-22 21:32
+1

**Comment by COLABORATI** [comment] 2015-05-26 20:08
Another usecase: upload picture and generate link for one user and this user can accept or deny publishing this picture. Very often needed if you make pictures of events and respect the privacy of the people photographed: they get send a link (needs email input somewhere on admin) and can view and download their picture plus they can decide if they want others to see this picture. Others might be another group, multiple groups, or everyone. 

yes, permission systems is something you want to plan from day 1 with your app :)

**Comment by ymoran00** [comment] 2015-05-27 18:55
+1

**Comment by computaholic** [comment] 2015-06-01 07:41
+1

**Comment by MarceFX** [comment] 2015-06-14 08:02
+1

I don't want some pals deleting pictures.

**Comment by Aidenir** [comment] 2015-06-25 15:24
Is anyone currently working on this feature?
I'm thinking of starting on it this weekend, and wanted to check first if anyone has begun work on it, to avoid multiple implementations of the feature.

**Comment by xxcram** [comment] 2015-06-25 20:06
I don't know how far Tobias is into this enhancement.
Which functionalities would you add to it? What's your idea behind the whole feature?

**Comment by Aidenir** [comment] 2015-06-25 20:41
Ok, the way I'm thinking of doing it is to do the login stuff mostly like they are now, except having a role assinged in the php session. This role will function like the current Admin and Guest roles work now. 

As for user management I'm thinking of adding a menu item in the top-left menu, which will produce a pop-up, in which new users can be created, and current users can be granted read or write privileges to any album. So by selecting a user you get a list of all albums, and beside the name one checkbox for read and one for write. 

In album view, under the share menu there will be a similar list of all the users, with read/write checkboxes beside them.

This way it would be easy to either grant a user privileges to any number of albums, or to grant multiple users privileges to any one album.

As for the actual implementaion of the access rights I haven't figured out how I will structure it completely, but I do have some ideas, for which I have to test a few SQL features to avoid having to do too much in php code..

I think the roles I will start with are just the current superuser which has all rights to everything, guest which have read rights to public albums, and visitor which has read and/or write the the albums for which the superuser has granted privileges.

This will result in a system which is not really multi-user per-say, more like single-user with better sharing possibilities. The most obvious use-case being a photographer as the superuser and his/her friends/family/customers as visitors (who will not have to keep multiple links saved somewhere)

**Comment by xxcram** [comment] 2015-06-25 21:47
Sounds good.

Some thoughts:
* Keep the sharing function (in case you don't want to create a new user for just one album)
* How would you manage users/album in the popup, when there are a lot of them (e.g. search field)?
* Which user can create and delete albums? Which can create users?

I'm interested about Tobias thoughts. I thing it's important to decide which functionality should go into before starting with the implementation. This way we can exclude different opinions and create a stable and useful feature.

To put the feedback from above together:
* Super User - has every privileges (view, edit and upload images, create user, delete albums)
* User - read/write access to one or multiple albums (can view, edit and upload images)
* User - read access to one or multiple albums (can view images)
* Guest - can view a single album shared through a link (password protected)
* Public - album is accessible to anyone through a link (no password protected, share over social media)

Do you agree with me?

**Comment by PeterTheOne** [comment] 2015-06-25 23:04
@Aidenir @xxcram Sounds great!

**Comment by Aidenir** [comment] 2015-06-26 07:24
@xxcram Response to your questions:
* Absolutely I would not touch the current sharing, my idea yesterday was based on the sharing popup when viewing a single photo. I see now this would not work, so perhaps having a separate button which pops up a modal dialog with the user list.
* To start with I don't think I will do a search field, but once the actual access rights code is working that would certainly be good to have.
* For this I see it as you put it in the summary: only the superuser has rights to create users and albums and settings read/write privileges to albums/users.

I too am interested in what @electerious thinks about this, since everyone could benefit if the implementation is according to the design he has in mind so he can merge with minimal changes, otherwise I will probably just end up doing it to fit my particular use-case.

**Comment by Aidenir** [comment] 2015-06-26 22:04
I started working on the database schema today.See 2c72b8bf2f74f6d4e35596451f50efb2042a2661.
Since the relationship between users and albums is a many-to-many I figured the best way to structure it is to use a privileges table, with foreign keys to the user and album id as well as a field for read and one for write. This allows to use something like this query when fetching the albums to display:
```
(SELECT * FROM lychee_albums a
  LEFT JOIN lychee_privileges u2a 
  ON a.id = u2a.album_id
  WHERE  u2a.user_id = 1
) 
UNION 
(SELECT * FROM lychee_albums a 
  RIGHT JOIN lychee_privileges u2a 
  ON a.id = u2a.album_id
  WHERE  u2a.user_id = 1
)
```

**Comment by squires** [comment] 2015-06-27 02:04
A junction table is certainly the right table structure for the permissions. I don't understand what that query is supposed to do, though. To get a list of albums the user has access to, just query the privileges table:

    select p.album_id
      from lychee_privileges p
     where p.user_id = 1

Or if you want to get the album data in the same query:

    select a.*
      from lychee_albums a
      join lychee_privileges p on (a.album_id = p.album_id)
     where p.user_id = 1

(Assuming that there won't be any entries in the privileges table where neither read nor write are granted.)

**Comment by Aidenir** [comment] 2015-06-27 06:52
What I tried to achhive with that query is to let the database do most of the heavy lifting. Instead of getting the ids a user has permissions to and then querying the db again.

The query I posted would do the same as the second one you posted, except that it would get read and write permissions into the result, which I figure can be handy when deciding which buttons to show in the GUI, which now that I think about it would not really be relevant if only the superuser has the rights to edit the album properties... But could be useful in the future at least :smile:

**Comment by squires** [comment] 2015-06-27 16:56
If you want the permissions as well, you can just add them to the above query:

    select a.*, p.read, p.write
      from lychee_albums a
      join lychee_privileges p on (a.album_id = p.album_id)
     where p.user_id = 1

**Comment by Aidenir** [comment] 2015-06-28 20:16
Aha ok, as you can probably figure out I'm quite the novice when it comes to SQL.

I have now gotten some of the user management working. Its possible to create and delete users (and login as these users of course), and the dialog for setting their permissions is there, but not functional yet.
![userview](https://cloud.githubusercontent.com/assets/1444625/8398092/e0a0f696-1de2-11e5-9beb-1250aa65e532.png)
![albumview](https://cloud.githubusercontent.com/assets/1444625/8398094/e3336c90-1de2-11e5-983a-3b4ecd9b6452.png)

The styling is not finilized either, just put it together so it worked. My thinking is that a similar view can be implemented in the album view, where instead of albums the users are listed.

Next up is implementing the access restrictions, and modifying the create user dialog to be able to choose what role new users should get.
If there is anything that looks strange in the commit 39ff762c8adebd469abb5077375da7643f657cb4 please let me know, so I can fix issues as soon as possible.

**Comment by PeterTheOne** [comment] 2015-07-05 13:15
The styling looks good :)

(I didn't look at the code)

**Comment by Aidenir** [comment] 2015-07-06 09:38
I got some more work done yesterday, and I'm not sure this implementation is the way to go, its clear that the frontend was not made with multi-user access in mind, so to keep the code as neat as @electerious has written it to start with, quite a lot would have to be rewritten. Although since this is a feature I need asap I will continue my work on it.

I got the role into the user-creation yesterday, and removed some of the options in the context menus when logged in as a regular user. For example a regular user is not allowed to set the dropbox link och manage users. I also reinforced this server side. 
Furthermore only albums which the user has an entry for in the privileges table is returned when fetching albums.

One point I'm not sure on is whether a regular user should be allowed to edit album attributes such as name and description? Does anyone have an opinion on this? Right now they're not, and they're also not allowed to delete or merge albums

**Comment by nikolauskrismer** [comment] 2015-07-16 20:59
+1

The demo looks great, although I would prefer a "invalid credentials" message (or similar) instead of just showing empty albums after entering a invalid username/password.

**Comment by moorestudios** [comment] 2015-09-21 23:17
@Aidenir - I'm glad to hear there is progress on this feature.  Since your last update in July, how close are you to completing V1?  I'd really like to start using this application but can't until multi-user is part of the build.  Thanks for your efforts.  

P.S.  The demo link is broken.

**Comment by Aidenir** [comment] 2015-09-22 06:34
To be honest I stopped working on it after my last update, since other projects were higher priority. 
But I'm pretty sure I will look into whats left to do and how to do it this week, when I get some sparetime (working on outages at work :( )
And the demo should be back up again tonight.

**Comment by Aidenir** [comment] 2015-09-22 20:34
> The demo looks great, although I would prefer a "invalid credentials" message (or similar) instead of just showing empty albums after entering a invalid username/password.

This issue is fixed now.

> P.S. The demo link is broken.

Fixed too.

I will try to resume development of this, but don't hold your breath, I have no idea when it'll work.

**Comment by moorestudios** [comment] 2015-09-22 21:17
Thanks @Aidenir - I've had a chance to look at the demo and things are looking good.  I noticed a few things that I'm sure you're aware of and working on:

Creating a user works but I don't get an option to save the permission type.  It just says 'back'. 

A delete option would be good idea where a user can upload photos but not delete them.

**Comment by Aidenir** [comment] 2015-09-22 21:25
Right now the permissions is not implemented (currently working on it ;)), but the idea is that the permissions are saved when they are changed. This will of course generate more traffic to the server, but it make implementation (and usage) way simpler.

Yes upload-only is a good idea... Perhaps "view, upload, delete" would be better than read, write?

**Comment by Colir** [comment] 2015-09-23 16:03
oh yes !!! the demo look so great !!!
Where i can get it ?

**Comment by Aidenir** [comment] 2015-09-23 16:16
@Colir Right now the only addition is that multiple users can login. All of them has full admin rights. When/If I finish it I will submit a pull request, meanwhile you can grab my branch "multiuser", however I think it has conflicts with the current master, will try to resolve them soon.

**Comment by Aidenir** [comment] 2015-09-23 20:40
This is the current status of this issue in my branch (will update comment continously):
Design
* [x] Design database tables needed

GUI
* [x] Add user management
* [x] Add user privilege management
* [ ] Per album user privilege selections (see earlier comments in this thread)

Security
* [ ] Enforce album viewing rights server-side
* [x] Enforce album viewing rights client-side
* [ ] Enforce album upload rights server-side
* [x] Enforce album upload rights client-side
* [ ] Enforce album deletion rights server-side
* [x] Enforce album deletion rights client-side

Should a normal user have the right to create albums? Adding another option for this would be quite hard, gui-wise, but for my use case I don't care, so unless someone else thinks differently non-admins will not be able to create albums...

**Comment by moorestudios** [comment] 2015-09-23 21:57
Looks like a good plan @Aidenir and looking forward to seeing the next version.  :+1:

**Comment by Colir** [comment] 2015-09-24 07:10
ok thanks you very much

**Comment by Aidenir** [comment] 2015-09-29 20:04
Ok, new status update.

Right now I would say my branch qualify as a beta of v1.

Supported:
- Create multiple users
- Assign either "admin" or "user" role
  - Admin: all rights to everything
  - User: can be allowed to view albums, upload photos to albums, and delete photos from albums. Obviously the user must be allowed to view to be able to upload or delete.
  - User: set view,upload, delete on specific albums.

Not implemented:
- Rights on smart albums. These are completely ignored so far.
- Modification of album or photo metadata. I haven't even tested this, but I assume all users are allowed to change all metadata right now.
- Modification of albums (delete, merge) by role user
- Creation of albums as user
- Moving photos by role user

The latest version is still available on https://demo.viha.se, as well as in my branch multiuser. New users are:
- admin:password
- user1:a
- user2:a
- user3:a

I really appreciate all feedback I can get on this, feel free to try to break the demo site. I have not tested it much. Since I no longer have the need for this function, I will not spend a lot of time on it unless someone else has some input in how the "not implemented" stuff should be designed.

**Comment by moorestudios** [comment] 2015-09-29 21:48
Thanks for the update @Aidenir .  Where are the options to allow users to view, add and delete per album?  I've created an album as the admin and I'm looking to give permission to a new user. Currently the user can only see smart albums.

**Comment by Aidenir** [comment] 2015-09-30 04:36
@moorestudios In the "manage users" in the top left corner, if you click on a user, you can see which albums he are allowed to. My plan is to have a similar view be available in the album view, where it will be possible to choose which users have access to the album, instead of which albums a user has access to.

**Comment by Cilyan** [comment] 2015-10-01 15:59
Hello there !
For my own server, I'm merging your work on top of the latest develop branch. This is still ongoing (at the moment, I just did the merge and I will start heavily testing), but this may be of interest to you, as the version of master you started on is a little old now.
I rebased the sessions feature and now the multiuser is on its way.
Thanks for implementing anyway, this work allowed me to get more familiar with the code of Lychee, I wouldn't have been able to implement what I wanted from scratch.

https://github.com/Cilyan/Lychee/tree/multiuser

**Comment by moorestudios** [comment] 2015-10-12 18:53
@cilyan - I've updated my demo site with your fork and it seems to be broken, at least for me.  Do you have it working on your end?  I can't authenticate any users...

**Comment by Cilyan** [comment] 2015-10-12 18:59
@moorestudios - No, not yet. I stumbled upon some problems with the Session cookie databases, and at the moment there's a problem with the javascript, which I'm trying to debug but I was a little stuck while getting the source maps. I'm still working on it, just had too few time the last past days to push anything solid on Github yet.

**Comment by engle2192** [comment] 2015-11-03 00:27
@Aidenir Ive downloaded your lychee multi user fork and after connecting to my database it asks to create a user name and password for the install. When I try to create one it keeps saying,

"function not found: Please Check the spelling of the called function" 

Are you able to assist me with this?

Thanks in advance

**Comment by Aidenir** [comment] 2015-11-23 12:16
@engle2192 A little late maybe, but I'll try and take a look at it tonight.

**Comment by lbdroid** [comment] 2016-01-11 15:14
I'm seeing the same thing as @engle2192

**Comment by lbdroid** [comment] 2016-01-11 15:40
Seems to be a problem in php/api.php where it is falling into guest access mode while creating the admin user. It is trying to execute the function Settings::setLogin, which doesn't exist in guest Guest.php. I was able to work around it by commenting out lines 66 and 67 and replacing with "if (true){" for creating the admin account, and then setting back afterwards.

**Comment by lbdroid** [comment] 2016-01-11 16:44
@Aidenir there are more problems with your branch;

1) I've come to understand that the mechanism for "sharing" an album with a regular user involves Settings --> Manage Users --> click the user, and it should open a window with a list of albums and checkboxes corresponding to the permissions granted to that user for that album. Unfortunately, the window is completely empty.

2) When logging in to a regular user without any albums, it spits out a blank page with a very cryptic error "Cannot execute function. Missing parameters or variables."

Following appears in logs;
[Mon Jan 11 11:34:58.866443 2016] [:error] [pid 5861] [client 127.0.0.1:60960] PHP Notice:  Undefined variable: database in /var/www/html/Lychee/php/modules/Album.php on line 217, referer: http://localhost/Lychee/
[Mon Jan 11 11:34:58.866461 2016] [:error] [pid 5861] [client 127.0.0.1:60960] PHP Notice:  Undefined variable: database in /var/www/html/Lychee/php/modules/Album.php on line 217, referer: http://localhost/Lychee/
[Mon Jan 11 11:34:58.866464 2016] [:error] [pid 5861] [client 127.0.0.1:60960] PHP Notice:  Trying to get property of non-object in /var/www/html/Lychee/php/modules/Album.php on line 217, referer: http://localhost/Lychee/

**Comment by lbdroid** [comment] 2016-01-11 16:54
More problems;
You are using two *reserved words* as column names in table lychee_privileges. Those reserved words are "read" and "write".

**Comment by lbdroid** [comment] 2016-01-11 17:03
Appears to be a bad query;

MariaDB [lychee]> SELECT a.id, a.title, p.view, p.upload, p.erase FROM lychee_albums a LEFT JOIN lychee_privileges p ON a.id = p.album_id AND p.user_id = 2;
ERROR 1054 (42S22): Unknown column 'p.view' in 'field list'

It appears that the view column was neglected from the table creation.

**Comment by lbdroid** [comment] 2016-01-11 17:39
@Aidenir: I made a pull request to your fork with the database column changes.

Interestingly, the problem with the first admin account creation seems only to be terminal in Chrome. In Firefox, F5 is adequate to get past the problem on the second attempt. Its still a bug, mind you, just not a fatal bug.

**Comment by Aidenir** [comment] 2016-01-11 19:07
@lbdroid I've merged your request, and I'll happily merge any other changes you make. 

As I'm sure you noticed life got in the way and all the free time I had to work on this just went out the window, so I'm not sure whether I will finish this implementation. But I will at least look into the bugs reported in this thread and see if I can do anything about them.

**Comment by Aidenir** [comment] 2016-01-11 21:21
Ok, I think I've solved the issue with the initial admin creation in commit  https://github.com/Aidenir/Lychee/commit/fc28037f38f1cf958867cbab310750d8349fe02b

As for a reegular user without any albums, that seems to work OK for me, meaning I only see the smart albums. However the error you added seems like a reasonable on, which I've fixed in https://github.com/Aidenir/Lychee/commit/7df1068cfc552b5351facfee2a47af7a29afbeff

And finally for the album selection for regular users, the window is blank if no albums exists(smart albums are completely separate), otherwise I see the albums I've created.

If you find any more issues please write about them. Otherwise I will probably not do much more here. What I'm missing is basically only selecting privileges for users based on album (now theres only album based on user), and this is not vital for my use-case anymore.

**Comment by lbdroid** [comment] 2016-01-12 19:05
I'm down to just one obvious bug that I'm struggling with. If I leave it for a while without logging out, and refresh it, it goes into a strange mode where it shows basically a grey page with a black line separating the header area from the body. No contents, no buttons. If I clear the applicable cookies, it goes back to the logged out screen and I can log in and use it as normal.

**Comment by lbdroid** [comment] 2016-01-12 19:33
[Tue Jan 12 14:32:42 2016] [error] [client 172.19.214.1] PHP Notice:  Undefined index: role in /data/lychee_image_host/php/api.php on line 66, referer: http://www.stage.ypdine.ca/imagehosting/
[Tue Jan 12 14:32:42 2016] [error] [client 172.19.214.1] 1 160d66a7f00a7882b64c486b83faaf1e  160d66a7f00a7882b64c486b83faaf1e, referer: http://www.stage.ypdine.ca/imagehosting/
[Tue Jan 12 14:32:42 2016] [error] [client 172.19.214.1] PHP Notice:  Undefined index: role in /data/lychee_image_host/php/api.php on line 70, referer: http://www.stage.ypdine.ca/imagehosting/

**Comment by Aidenir** [comment] 2016-01-12 19:39
@lbdroid Yes I'm seen that issue as well, but I haven't been able to find the cause.

How did you get those log lines? Is it when the above issue is present?

If that is the case I think it has something to do with the php session expiring, and a session cookie still being present and active, but since Session::init is not called the php session doesn't contain the required variables (login, role and identifier).

**Comment by lbdroid** [comment] 2016-01-12 20:04
I may be having trouble with your commit https://github.com/Aidenir/Lychee/commit/fc28037f38f1cf958867cbab310750d8349fe02b

After I pulled that one in, it started persistently going into the blank page mode, even after wiping my browser profile.

**Comment by Aidenir** [comment] 2016-01-12 20:08
Do you have any steps to reproducce it? I tried with a fresh pull and a clean database and I can't get the blank page unless I let the php session expire.

**Comment by lbdroid** [comment] 2016-01-12 20:20
Never mind that. Its working fine on my test rig.

**Comment by electerious** [comment] 2016-01-12 20:27
Hey everyone, please stop using this issue for commenting a fork. Forks have their own issues. New "unrelated" comments will be deleted. Thanks!

**Comment by lbdroid** [comment] 2016-01-12 20:31
@electerious could you please clarify... while it may be a fork, everything is a fork until it reaches a stage where it can be merged back, and in my mind, that makes it a valid discussion for this forum. That is, unless upstream has no intention of accepting this feature when it is finally ready...?

**Comment by electerious** [comment] 2016-01-12 21:05
It's fine to discuss the general direction of forks, but I don't want that this issue turns into a support page. Issues related to the fork (e.g. "It's not working") should be postes in the issues of the fork.

**Comment by lbdroid** [comment] 2016-01-12 21:07
Ok, fair enough.

@Aidenir; could you add an issue tracker to your fork?

**Comment by Aidenir** [comment] 2016-01-12 21:10
@electerious ok sounds reasonable.

@lbdroid done.

**Comment by Treer** [comment] 2016-05-11 04:37
What's the status of this? Has @Aidenir run out of time to work on it?

If so, did the approach taken by Aidenir work without drawbacks - should someone else try to manually rebase the multi-user commits to the current Lychee, or were there still issues to resolve?

**Comment by mvanrompuy** [comment] 2016-05-15 22:26
@Treer: As I needed the multi-user feature for the setup I had in mind, I've tried to get the branch created by @Aidenir updated to a more recent Lychee version (v3.0.9). Didn't have much time to work on it recently, have the website working with some bugs:

- Login not auto-forwarding after successful login
- Menu button not always reacting
- I didn't initially notice that the video support feature was also included in Aidenir's fork. Not sure if this correctly works.

I'm currently trying to get it into a clean/stable state before updating the fork to the latest Lychee version.

**Comment by caspre24** [comment] 2016-07-29 23:52
I very much like the multiuser features myself, so I started separating @Aidenir's multiuser branch from the video support. My branch https://github.com/caspre24/Lychee/tree/multiuser is now based on v3.0.2 which is quite old.
I hope I find the time to merge with the lastest master the next days. In the meantime this branch might serve as a (hopefully clean) base to get multiuser support into Lychee, as @Treer suggested =)

**Comment by petrk94** [comment] 2016-10-28 10:09
The Multiuser tree is not longer available.
Is it still in work?

**Comment by caspre24** [comment] 2016-10-29 10:13
@petrk94 is available again. Seems I deleted it during cleanup of my github account. I found another solution that I find more practical so I won't be developing on Lychee anymore.

**Comment by petrk94** [comment] 2016-10-29 10:57
@caspre24 what you have found for a solution? 
So I can use Lychee as for multiuser?

**Comment by caspre24** [comment] 2016-10-29 11:01
I'm now using piwigo with a bootstrap-based theme.
I'm not sure, how stable the multiuser-branch is.

**Comment by petrk94** [comment] 2016-10-29 11:21
Ah i see, I like the interface of lychee. Piwigo doesn't shows nice.
I want to use it as a free web service for photos.

Am 29.10.2016 13:01 schrieb "Carsten Sprung" <notifications@github.com>:

**Comment by mvanrompuy** [comment] 2016-11-05 00:12
Checking in again, after losing track of this issue for some time.

Currently have Lychee v3.1.5 up with basic multiuser implementation.

I have a server hosting a working lychee install based on the latest hash (3df88ba1298c46acadb07fbf6ce2af7fb0d05d5f) and I'm using that to check for further bugs.

Current list of issues I need to look into:
- Starring of photo needs to be stored in separate table so it isn't shared between users.
- Moving a photo while creating that album, only creates the album without moving the photo to it.
- Video support is in this branch, but untested. Will need to be stripped out to a separate branch.
- Code cleanup will be needed: debugging prints, adding comments, ...
- ....

I'm currently further cleaning up and checking for other bugs. If anyone does try my code in the meantime, be sure to report any problems you find.

I only recently learned about @caspre24's code. I might compare my current code against his changes, not sure far along he was..

**Comment by petrk94** [comment] 2016-11-05 09:46
Hello,

thanks for the informations. I want to use it as a service in a local Free Wifi Community called "Freifunk" in Germany. Thats why mulituser support is necessary.
My current problem is to install it on the server, because it denied the mysql server login and I dont know why this issue happens.

**Comment by mvanrompuy** [comment] 2016-11-05 10:53
@petrk94 If you're seeing this problem only on my fork. Please create an issue there and I'll take a look at it.

**Comment by petrk94** [comment] 2016-11-05 11:03
@mvanrompuy I dont have tried your fork, are you developing it by yourself or only sometimes?

**Comment by mvanrompuy** [comment] 2016-11-05 19:07
We'll I'm trying to get a multi-user install up and running for a family project. So I'm currently implementing it on my own.

Once I'm happy with the implementation I would also be open to other improvements that would be needed to try and merge this feature to master branch. So any input is welcome.

**Comment by petrk94** [comment] 2016-11-05 19:53
@mvanrompuy 
this would be great :) please let us know when you have it done, the multiuser part is really important for me. In 2 weeks I can send you a screenshot of the Lychee issue with mysql, before I dont have internet which is fast enough to use it for working :/

**Comment by mvanrompuy** [comment] 2017-01-15 15:49
Currently have a fairly stable multi-user branch on my account. Code needs some cleaning up and bugfixes, which I'm working on. If anyone's interested in helping feel free to report issues on my fork after trying out my code.

**Comment by petrk94** [comment] 2017-01-15 16:18
@mvanrompuy  I would like, but as freelancer I have not enough time. And I can not PHP, only HTML in this case :/

**Comment by scerazy** [comment] 2017-05-30 14:01
+1

**Comment by alleyoopster** [comment] 2017-07-09 11:17
+1 for the multi-user, thanks for working on it

**Comment by Shadowsilk** [comment] 2017-08-16 09:55
+1

**Comment by Ludvins** [comment] 2017-11-07 23:11
is anyone working on this?

**Comment by 70m43** [comment] 2017-11-26 18:23
+1

**Comment by mbrgm** [comment] 2017-11-26 22:32
Github has a emoji/reaction function, where you can '+1' ideas without spamming watchers' inboxes. Please use it! Thank you!

**Comment by drewphoto** [comment] 2018-01-26 13:58
Sorry I'm late to the party - just found this.
Firstly - thanks for developing this package.
Multi-user would be really useful for my workflow.
I think you've already identified most of the functionality.
Context : 
My main portfolio site is built in WordPress, but I need way to share 'proof' images for approval before undertaking post-processing.
I've used Dropbox in the past for this, but they've now limited the ability to download an entire folder.

User case (hope you still want these) ...
I undertake shoots with multiple participants (models, Make-up Artists, stylists). Each may have 200+ images.
I'd like each of the participalnts to be able to select a few for post-processing (basically, a user level star system), so I can tell who has selected which images.
Ideally, I'd like them to be able to filter a toggle (showing only their starred images) to see which images they've selected.
Again, Ideally (and I realise this is probably a bigger development), I'd like them to be able to comment on the image, and for that comment to be tagged with their user-id.

**Comment by jeyca** [comment] 2018-09-22 19:40
is anyone actively working on this?

**Comment by electerious** [comment] 2018-09-22 20:33
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.

**Closed by electerious** 2018-09-22 20:33 UTC
