### ISSUE TITLE
Loading animation in photo view

### ISSUE THREAD

**Issue by k4r7u** [electerious/Lychee#361] opened 2015-06-13 10:55 UTC
If a photo has already been viewed in the browser, it is shown with something like a zoom-in animation. This looks really nice and feels very responsive. But if a photo hasn't been viewed yet, it is loaded from the top to the bottom. This looks like 10 years back, when you had to wait for a picture to be downloaded. 
While this takes only 1 to 2 seconds for me, it is kind of annoying. It would be great if instead some kind of spinner could be shown until the image is loaded completely, to be then displayed with the same zoom-in effect as already viewed photos.

**Comment by LudovicRousseau** [comment] 2015-06-13 11:31
It looks like your request is a duplicate of #241.

My preferred solution would be to preload the next picture as requested in #185.

**Comment by k4r7u** [comment] 2015-06-13 11:46
If I am not mistaken #241 is talking about albums, not pictures itself.
Well #185 is similar, but not quit what I meant. If the next picture is preloaded while I look at the current picture, this works only if I look long enough at the current one. If I switch to the next picture fast, there hasn't been time to preload this picture. What I suggest would be some kind of spinner to be shown in every case where a picture is not yet fully loaded/preloaded.

**Comment by electerious** [comment] 2015-06-13 15:45
Lychee uses CSS to load/display the photo. This allows me to use `background-size: contain` to fit the photo inside the photo area without using JS. The problem with this solution is that there's no way to determine if the photo has finished loading. This information is essential when we want a loading bar.

Another attempt would be [CSS3 object-fit/object-position](http://caniuse.com/#feat=object-fit), but the browser-support is still bad. `object-fit` also solves the problem of issue #185.

**Comment by kgraefe** [comment] 2015-07-01 20:26
Couldn't you display the loading animation by default and use the preload mechanism from #185 to fetch the current image and replace the animation with the image when it is loaded?

Is there a reason to not use JS to load the image? (Is Lychee intended to work without JS?)

**Comment by k4r7u** [comment] 2015-07-03 09:38
This is exactly what I meant.

**Comment by electerious** [comment] 2016-03-04 22:32
Finally found a way to use an `<img>` for the photo. It should now be possible to add a loading animation while waiting for the photo.

**Comment by electerious** [comment] 2018-09-22 20:52
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.

**Closed by electerious** 2018-09-22 20:52 UTC
Labels: enhancement, low priority
