### ISSUE TITLE
Upload in Safari only adds first picture

### ISSUE THREAD

**Issue by bb-Ricardo** [electerious/Lychee#509] opened 2016-04-12 06:59 UTC
Hi,

I'm having trouble uploading pictures with Safari on OSX (all latest versions). Firefox and Chrome are working properly. Using "master" branch of Lychee

When I upload a file it doesn't show the upload in percent and says "Finished". Then nothing happens.

No Error in Lychee Log or Safari console.

Any idea how to start troubleshooting this one?

Thank you

**Comment by electerious** [comment] 2016-04-15 15:42
Couldn't reproduce the problem (Safari Version 9.1 (11601.5.17.1)).

You could inspect the network requests to see what's happening. Does Safari actually send anything to the server?

**Comment by electerious** [comment] 2016-04-22 07:46
Any additional information?

**Comment by electerious** [comment] 2016-04-22 08:02
Going to close this issue in favor of https://github.com/electerious/Lychee/issues/522#issuecomment-211389493 which seems to be the same problem.

**Closed by electerious** 2016-04-22 08:02 UTC
