### ISSUE TITLE
Lychee only uploads the first file when multiple images are selected

### ISSUE THREAD

**Issue by Hund** [electerious/Lychee#522] opened 2016-04-18 11:35 UTC
### Detailed description of the problem

Lychee only uploads the first file when multiple images are selected. It uploads the first file with the message "Success" and then it just halts, no error message, no nothing. And I have to reload the page to escape.

### Steps to reproduce the issue

Select multiple files and then start uploading them.

### Diagnostics

```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version:  3.1.0
DB Version:      030100
System:          Linux
PHP Version:     5.5
MySQL Version:   50547
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      2.1.1-dev
Plugins:  
```
### Log

The only thing mentioned in the log is this:

    2016-04-18 13:26:42 - notice - Lychee\Modules\Photo::add (219) 	- Skipped adjustment of photo (old-sketch--2004_16675160987_o)

### Browser and system

Client: Arch Linux with Pale Moon 26.2.1.
Server: Ubuntu 14.04.

**Comment by electerious** [comment] 2016-04-18 11:42
Can you take a look at the network inspector of your browser to confirm that it's actually sending only one file? Does this happen in every browser and with all photos?

**Comment by Hund** [comment] 2016-04-18 11:49
Oh, it worked with Chromium. :/ Didnt think or double checking with another browser.

I checked the inspector, but I'm not sure what I'm looking for?

**Comment by bb-Ricardo** [comment] 2016-04-18 13:51
seems related to #509

**Comment by electerious** [comment] 2016-08-28 12:43
Closing this issue as I'm not able to reproduce it. Let me know if the problem still exists.

**Closed by electerious** 2016-08-28 12:43 UTC
