### ISSUE TITLE
Upload animation is not working

### ISSUE THREAD

**Issue by vdonnefort** [electerious/Lychee#388] opened 2015-08-14 08:05 UTC
If photos upload is working properly, the loading animation is broken.

See the following screenshot of the import of a "test.jpg" image.

I'm using Lychee 3.0.5 and I have to problem with nginx and apache.

![lychee-capture](https://cloud.githubusercontent.com/assets/3084220/9269508/b8880788-426a-11e5-8486-54206fae258d.png)

**Comment by electerious** [comment] 2015-08-15 09:09
Which browser (+ version) are you using?

**Comment by vdonnefort** [comment] 2015-08-17 08:01
Firefox 40.0. I don't see this problem with Chromium.

**Comment by electerious** [comment] 2015-08-21 20:02
Works fine in Firefox 40.0.2 on OS X. Not sure why this is happening.

**Comment by TIXXEN** [comment] 2015-08-24 11:10
It also happens in Firefox 40.0.2 on OS X
![bildschirmfoto 2015-08-24 um 13 04 07](https://cloud.githubusercontent.com/assets/1708492/9438787/60ce5412-4a61-11e5-88cc-c0ec14aafe72.png)

**Comment by electerious** [comment] 2015-09-23 07:55
I'm still unable to reproduce the problem. Could the issue be cased by a plugin (e.g. Adblock)?

**Comment by vdonnefort** [comment] 2015-09-23 08:00
It works now, with Firefox __40.0.3__ and Lychee __3.0.6__

**Comment by electerious** [comment] 2015-09-23 08:04
@TIXXEN Can you confirm that it's now working for you in Firefox 40.0.3, too?

**Comment by TIXXEN** [comment] 2015-09-23 11:33
Yes it's now working. Lychee 3.0.6 with Firefox 41.0

**Comment by FlorianMiesenberger** [comment] 2015-09-23 12:19
Thank you for solving this problem! :+1:

**Comment by electerious** [comment] 2015-09-23 12:20
I haven't done anything ;) Guess it was a Firefox bug. Glad that's fixed now.

**Closed by electerious** 2015-09-23 12:20 UTC
