### ISSUE TITLE
Dropdowns do not work in chrome (3.0.0)

### ISSUE THREAD

**Issue by TheZoker** [electerious/Lychee#345] opened 2015-05-06 22:09 UTC
I have some issues with update 3.0.0:
- In chrome the dropdowns do not work (in firefox they do).
- There is no "pointer" courser on the dropdowns and links

**Comment by electerious** [comment] 2015-05-07 19:10
Are you talking about the context-menus or the dropdowns (Settings -> Change Sorting)?

**Comment by TheZoker** [comment] 2015-05-07 19:11
Im talking about e.g. the "login" button or the settings menu or the "add new image" button

**Comment by electerious** [comment] 2015-05-07 19:15
That's interesting. Works fine on OS X with Chrome 42.0.2311.135 (64-bit). Are you using an extension which could case this problem (Chrome Extension)?

**Comment by TheZoker** [comment] 2015-05-07 19:19
Im on Windows chrome Version 42.0.2311.135 m...
I disabled all plugins that could cause this problem (e.g. adblocker, FlashControl...)

Can you try it on my page:
http://zoker.me/images/

**Comment by electerious** [comment] 2015-05-07 19:25
Works fine, even on your site. Not sure if there's a difference between OS X and Windows Chrome which could case this problem. Could you attach a short video of the problem?

**Comment by TheZoker** [comment] 2015-05-07 19:35
How can I attach a video here? :P

**Comment by electerious** [comment] 2015-05-10 16:26
Guess you need to use a sharing-service ;)

**Comment by dotcomUNDERGROUND** [comment] 2015-05-12 20:54
I get the same issue over Google Chrome on Windows. Clicking on that login icon simply doesn't do anything.

Here is a video of it: http://www.mediafire.com/watch/bmv8z9lw8szvb0r/Lychee_Chrome_Issue.wmv

**Comment by electerious** [comment] 2015-05-13 18:35
Strange. Just tested on Win7 with the newest version of Chrome and everything worked fine. Same on OS X. Could you try in incognito mode with all plugins disabled?

**Comment by dotcomUNDERGROUND** [comment] 2015-05-13 19:06
I was actually running in incognito mode when making the video. Version 42.0.2311.152 m on windows 8.1

**Comment by electerious** [comment] 2015-05-14 10:45
Now tested on Win 8.1 and it worked well, too. I've no idea.

Is there an error in the browser console?

**Comment by dotcomUNDERGROUND** [comment] 2015-05-14 11:40
You mean the java script console there on Chorome?

Nothing shows up there when i click on the icon.
https://screenshot.felinetech.net/15/0514173515.jpg

**Comment by electerious** [comment] 2015-05-14 12:41
No error and no way to reproduce it (at least for me). So bad :-/ Would really like to find the reason.

**Comment by dotcomUNDERGROUND** [comment] 2015-05-14 20:42
:(

Can't it be possible to switch this to the way it was in previous version? That was working fine.

**Comment by electerious** [comment] 2015-05-14 21:03
Tons of stuff has been changed. I've no idea what's the exact reason for the problem.

**Comment by sapek** [comment] 2015-06-13 21:29
I see the same problem, Windows 8.1, Chrome 43.0.2357.81 m, incognito window.

**Comment by electerious** [comment] 2015-06-13 21:31
@sapek Any idea what could case this problem? Which plugins are you using (if any activated during incognito)?

**Comment by sapek** [comment] 2015-06-13 21:44
Don't know. I'm not much of a front-end guy. All links on top don't work, even back button. Also the slide-in button to move to next photo doesn't work. I have no extensions enabled in incognito. There is no errors or output in browser dev tools/console. The same problem on your demo site so this is not an install issue.

If you want to put in some diagnostics I can run from a branch (or if you prefer send me a git patch).

**Comment by sapek** [comment] 2015-06-13 22:05
Navigating between photos with left/right arrow keys also doesn't work in Chrome.

**Comment by sapek** [comment] 2015-06-13 22:16
One more data point: the i icon doesn't work when clicked by the i shortcut does work and displays the info box.

**Comment by sapek** [comment] 2015-06-13 22:39
OK, I have some more info that might help you narrow this down: I can repro the problem on a device with touch screen (Surface Pro 3) and on that device the site does work with touch events but doesn't work with mouse. I can't repro on regular desktop with Windows 8 (with no touch screen).

**Comment by dotcomUNDERGROUND** [comment] 2015-06-15 11:55
I experience the same as "sapek" said. mouse click doesnt work. but taping it (on touch screen) works!

on a windows 8.1 touch screen laptop (thinkpad helix)

**Comment by electerious** [comment] 2015-06-16 19:25
Got it! It's the `touchend` event casing the problem.

```js
var eventName = ('ontouchend' in document.documentElement) ? 'touchend' : 'click';
```

The if returns true because of the touchscreen and Lychee continues to use `touchend` which isn't working with a mouse. Could be hard to get a correct detection without dropping `touchend` complexity. Ideas are welcome and thanks for the help! :)

**Comment by electerious** [comment] 2015-06-28 11:21
Should be fixed now. Please let me know if it works.

**Comment by sapek** [comment] 2015-06-28 16:59
Works now on Surface. Thanks!

**Comment by electerious** [comment] 2015-06-28 17:00
Great to hear that it finally works! :)

**Comment by dotcomUNDERGROUND** [comment] 2015-07-02 19:43
Still not working for me on Thinkpad Helix.

**Comment by electerious** [comment] 2015-07-09 10:03
@dotcomUNDERGROUND You right! Just figured out that the problem has only been fixed for some buttons. There're still a few missing.

**Comment by TheZoker** [comment] 2015-07-09 10:12
Can confirm its not fixed! e.g login button does not work.

**Comment by electerious** [comment] 2015-07-09 16:37
@TheZoker @dotcomUNDERGROUND Please take a look at the develop-branch and let me know if it's (finally) working.

**Comment by TheZoker** [comment] 2015-07-09 16:58
Yea seems working :)

**Comment by electerious** [comment] 2015-07-09 16:59
:tada:

**Comment by dotcomUNDERGROUND** [comment] 2015-07-09 18:09
Yes, seems to be working fine now. Thanks!

**Closed** 2015-07-09 18:26 UTC
