### ISSUE TITLE
Receiving Out of range value for column 'takestamp' at row 1 with some pictures

### ISSUE THREAD

**Issue by josefrvaldes** [electerious/Lychee#585] opened 2016-08-01 13:38 UTC
As the title says, I'm receiving this failure in Lychee/plugins/Log when updating some pictures.

**Comment by electerious** [comment] 2016-08-04 08:45
Could you show me the database entries of the affected pictures? Not sure why takestamp should be out of range.

**Comment by josefrvaldes** [comment] 2016-08-04 14:38
I'm sorry but I don't use Lychee anymore.. If you give me a few days I could make a test Lychee install just to see the fail again and tell it to you, but now I don't have any Lychee installation and I can't tell you more information.

I'm really sorry.

**Comment by qligier** [comment] 2016-08-09 18:14
It would help to see the Exif info of the image.
If you use PHP < 5.1.0, it's possible that [strtotime](https://github.com/electerious/Lychee/blob/master/php/Modules/Photo.php#L865) fails on your image and [returns -1](http://php.net/manual/en/function.strtotime.php#refsect1-function.strtotime-returnvalues). The column is unsigned, so trying to insert the value trows an error.

**Comment by electerious** [comment] 2016-08-28 12:58
Closing this issue as I'm not able to reproduce it. Thanks for the report anyway!

**Closed by electerious** 2016-08-28 12:58 UTC
